In [113]:

    # load libraries
    from keras.datasets import imdb
    from keras.models import Sequential
    from keras.layers import Dense, Flatten
    from keras.layers.convolutional import Conv1D, MaxPooling1D
    from keras.layers.embeddings import Embedding
    from keras.preprocessing import sequence
    import tensorflow as tf
    from tensorflow import keras
    

In [114]:

    # load data and Set the number of words we want
    top_words = 5000 # number of feature
    input_length = 500#size for each feature is 500


In [116]:

    # Load data and target vector from movie review data
    
    (X_train, y_train), (X_test, y_test) = tf.keras.datasets.imdb.load_data(num_words=top_words)
    
    print(X_train.shape); 
    print("-------------------------------------")
    print(X_train)
    
    

(25000,)
-------------------------------------
[list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 2, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 2, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 2, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 2, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 2, 19, 178, 32])
 list([1, 194, 1153, 

In [119]:

    # Convert movie review data to feature matrix
    X_train = sequence.pad_sequences(X_train, maxlen=input_length) # for Embedding want the fixed size 500 for each feature
    # for example if x_train[0] = [1,2] 1,2 the is the index of the words
    #after feature matrix x_train[0] = [1,2 ,0,0,0,....] becase have the fixd length for all feature to enter to Embedding
    print(X_train.shape); print(X_train)

    X_test = sequence.pad_sequences(X_test, maxlen=input_length)
    print(X_test.shape);  print(X_test)


(25000, 500)
[[   0    0    0 ...   19  178   32]
 [   0    0    0 ...   16  145   95]
 [   0    0    0 ...    7  129  113]
 ...
 [   0    0    0 ...    4 3586    2]
 [   0    0    0 ...   12    9   23]
 [   0    0    0 ...  204  131    9]]
(25000, 500)
[[   0    0    0 ...   14    6  717]
 [   0    0    0 ...  125    4 3077]
 [  33    6   58 ...    9   57  975]
 ...
 [   0    0    0 ...   21  846    2]
 [   0    0    0 ... 2302    7  470]
 [   0    0    0 ...   34 2005 2643]]


In [118]:
print(X_train)

[[   0    0    0 ...   19  178   32]
 [   0    0    0 ...   16  145   95]
 [   0    0    0 ...    7  129  113]
 ...
 [   0    0    0 ...    4 3586    2]
 [   0    0    0 ...   12    9   23]
 [   0    0    0 ...  204  131    9]]


In [108]:

    # setup a CNN network
    model = Sequential()# input_length = 500 number of colunm
    model.add(Embedding(5000 , 32, input_length=500))
    model.add(Conv1D(filters=32, kernel_size=3, padding='same', activation='relu'))
    model.add(MaxPooling1D(pool_size=2))
    model.add(Flatten())
    model.add(Dense(250, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])



In [109]:
    model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_5 (Embedding)     (None, 500, 32)           160000    
                                                                 
 conv1d_5 (Conv1D)           (None, 500, 32)           3104      
                                                                 
 max_pooling1d_5 (MaxPooling  (None, 250, 32)          0         
 1D)                                                             
                                                                 
 flatten_5 (Flatten)         (None, 8000)              0         
                                                                 
 dense_10 (Dense)            (None, 250)               2000250   
                                                                 
 dense_11 (Dense)            (None, 1)                 251       
                                                      

In [112]:

    # Fit the model
    model.fit(X_train, y_train, validation_data=(X_test, y_test), 
              epochs=3, batch_size=128, verbose=1)


Epoch 1/3
148/196 [=====================>........] - ETA: 8s - loss: 0.2480 - accuracy: 0.9003

KeyboardInterrupt: 

In [ ]:

    # Final evaluation of the model
    scores = model.evaluate(X_test, y_test, verbose=1)

    print("Accuracy: %.2f%%" % (scores[1]*100))
  

In [81]:
import matplotlib.pyplot as plt
plt.plot(history.history['loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train'] , loc='upper left')
plt.show()

NameError: name 'history' is not defined